name: Run Robot Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Instalar Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Configurar cache do pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Instalar pacotes do sistema
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-4-1 libvpx9 libevent-2.1-7 libopus0 libgstreamer-plugins-base1.0-0 woff2

    - name: Encerrar processos do Chrome e WebDriver
      run: |
        pkill -f "chromedriver" || true
        pkill -f "chrome" || true

    - name: Definir diretório temporário para navegador
      run: echo "USER_DATA_DIR=/tmp/chrome-${RANDOM}" >> $GITHUB_ENV

    - name: Instalar dependências do Python
      run: |
        pip install -r requirements.txt

    - name: Rodar testes do Robot Framework
      run: robot --variable BROWSER:chrome --variable HEADLESS:True --variable USER_DATA_DIR=${USER_DATA_DIR} tests/