name: Run Robot Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Instalar Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Configurar cache do pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Instalar pacotes do sistema
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-4-1 libvpx9 libevent-2.1-7 libopus0 libgstreamer-plugins-base1.0-0 woff2

    - name: Instalar Google Chrome
      run: |
        if ! command -v google-chrome-stable &> /dev/null; then
          echo "Google Chrome não está instalado. Instalando agora..."
          sudo apt-get update
          wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb || sudo apt-get install -f -y
        fi
        ls -lh /usr/bin/google-chrome-stable
        google-chrome-stable --version || echo "Erro ao obter a versão do Chrome"

    - name: Verificar instalação do Google Chrome
      run: |
        which google-chrome-stable || echo "Google Chrome não encontrado!"

    - name: Extração manual da versão do Chrome
      run: |
        CHROME_PATH=$(which google-chrome-stable || echo "/usr/bin/google-chrome-stable")
        if [ -f "$CHROME_PATH" ]; then
          CHROME_VERSION=$($CHROME_PATH --version | awk '{print $3}')
          echo "Versão do Google Chrome: $CHROME_VERSION"
        else
          echo "Erro: Google Chrome não encontrado!"
          exit 1
        fi

    - name: Instalar ChromeDriver versão fixa
      run: |
        wget -q https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver

    - name: Testar execução do Chrome
      run: |
        google-chrome-stable --version
        google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://example.com & sleep 5
        pkill chrome

    - name: Instalar dependências do Python
      run: |
        pip install -r requirements.txt

    - name: Rodar testes do Robot Framework
      run: robot --variable BROWSER:chrome tests/